<%@ Page Title="" Language="C#" MasterPageFile="~/Controllers/Site1.Master" AutoEventWireup="true" CodeBehind="users_page.aspx.cs" Inherits="OnMyWay2.Controllers.users_page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

		    <form id="form1" runat="server">

          <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="false"
              BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical"
              AutoGenerateDeleteButton="True"
              AutoGenerateEditButton="True" 
              OnRowEditing="OnRowEditing" 
              OnRowCancelingEdit ="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting1" OnRowUpdating="GridView1_RowUpdating1"
              
              DataKeyNames="user_id">
                  <Columns>
                      
                    <asp:BoundField DataField="user_name" HeaderText ="User name" />
                    <asp:BoundField DataField="user_phone" HeaderText ="phone" />
                    <asp:BoundField DataField="user_password" HeaderText ="User pass" />
                       <asp:BoundField DataField="user_id" HeaderText ="User id" />
                         <asp:BoundField DataField="user_gender" HeaderText ="Gender" />
                         <asp:BoundField DataField="user_photo" HeaderText ="Photo" />

                  </Columns>
        </asp:GridView>
       <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
            <tr>
                <td style="width: 150px">
                    UserName:<br />
                    <asp:TextBox ID="UserNameTxt" runat="server" Width="140" />
              
                <td style="width: 150px">
                    Phone:<br />
                    <asp:TextBox ID="PhoneTxt" runat="server" Width="140" />
                </td>
                 <td style="width: 150px">
                    Password:<br />
                    <asp:TextBox ID="PasswordTxt" runat="server" Width="140" />
                </td>
                 <td style="width: 150px">
                    Gender:<br />
                    <asp:TextBox ID="GenderTxt" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    <asp:Button ID="btnAdd" runat="server" Text="Add New * " OnClick="btnAdd_Click" />
                </td>
            </tr>
        </table>
          <br />
      </form>
</asp:Content>
